
package client.random;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandomWebService", targetNamespace = "http://random/", wsdlLocation = "http://localhost:8888/rs?wsdl")
public class RandomWebService
    extends Service
{

    private final static URL RANDOMWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDOMWEBSERVICE_EXCEPTION;
    private final static QName RANDOMWEBSERVICE_QNAME = new QName("http://random/", "RandomWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/rs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDOMWEBSERVICE_WSDL_LOCATION = url;
        RANDOMWEBSERVICE_EXCEPTION = e;
    }

    public RandomWebService() {
        super(__getWsdlLocation(), RANDOMWEBSERVICE_QNAME);
    }

    public RandomWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDOMWEBSERVICE_QNAME, features);
    }

    public RandomWebService(URL wsdlLocation) {
        super(wsdlLocation, RANDOMWEBSERVICE_QNAME);
    }

    public RandomWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDOMWEBSERVICE_QNAME, features);
    }

    public RandomWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandomService
     */
    @WebEndpoint(name = "RandomServicePort")
    public RandomService getRandomServicePort() {
        return super.getPort(new QName("http://random/", "RandomServicePort"), RandomService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomService
     */
    @WebEndpoint(name = "RandomServicePort")
    public RandomService getRandomServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://random/", "RandomServicePort"), RandomService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDOMWEBSERVICE_EXCEPTION!= null) {
            throw RANDOMWEBSERVICE_EXCEPTION;
        }
        return RANDOMWEBSERVICE_WSDL_LOCATION;
    }

}
